import Link from "next/link";
import { ArrowRight, PackageOpen, Smartphone, Download } from "lucide-react";
import data from "../data/packages.json";
type Package = {slug:string;name:string;icon?:string;category:string;priceCents:number;summary:string};
const packages = data as Package[];

export default function Home() {
  const live = process.env.NEXT_PUBLIC_COMMERCE_ENABLED === "1";
  return <main>
    <header className="nav"><Link className="brand" href="/"><span>J.</span> JimWas Repo</Link><nav><Link href="/packages">Packages</Link><a href="#install">Add repo</a></nav><Link className="nav-cta" href="/packages">Browse tweaks <ArrowRight size={16}/></Link></header>
    <section className="section featured-collection" id="packages"><div className="section-head"><div><p className="eyebrow">THE COLLECTION</p><h2>Explore the tweaks</h2><p>Built to make the little details feel right.</p></div><Link href="/packages">View all packages <ArrowRight size={17}/></Link></div>{packages.length ? <div className="cards">{packages.map((item)=><Link className="card" href={`/packages/${item.slug}`} key={item.slug}><div className="card-icon">{item.icon?.startsWith("/") ? <img src={item.icon} alt=""/> : item.icon || "✦"}</div><div className="card-meta">{item.category}<b>{item.priceCents ? `$${(item.priceCents/100).toFixed(2)}` : "Free"}</b></div><h3>{item.name}</h3><p>{item.summary}</p><span>View package →</span></Link>)}</div> : <div className="empty"><div className="empty-icon"><PackageOpen size={30}/></div><h3>The first release is on its way</h3><p>Packages will appear here as soon as they are ready to install.</p></div>}</section>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">INDEPENDENT IOS TWEAKS</p><h1>Make your iPhone <em>your own.</em></h1><p className="intro">Thoughtful tweaks, built and maintained by JimWas. Find the tools you want, install them from one source, and get updates in your package manager.</p><div className="actions"><Link className="primary" href="/packages">Explore packages <ArrowRight size={18}/></Link><a className="secondary" href="#install">How to add the repo</a></div>{!live&&<small>JimWas Recorder is listed at $34.99; checkout opens at launch</small>}</div><div className="visual" aria-hidden="true"><div className="halo"/><div className="phone"><div className="phone-top">9:41 <span>◕ ▰</span></div><div className="phone-title">Your device.<br/>Your rules.</div><div className="app-grid"><i>✳</i><i>◈</i><i>⌘</i><i>✦</i></div><div className="dock">●　●　●　●</div></div><div className="floating upper"><Smartphone size={19}/> Made for iOS</div><div className="floating lower"><Download size={19}/> Simple installs</div></div></section>
    <section className="section install" id="install"><div><p className="eyebrow">GET STARTED</p><h2>One source.<br/>All the updates.</h2><p>Add the repo URL to Sileo or Zebra on a jailbroken device. Installed packages will receive updates through your package manager.</p><ol><li>Open your package manager</li><li>Go to Sources and choose Add</li><li>{live?"Enter the repo URL shown here":"Enter the repo URL once it launches"}</li></ol></div><div className="install-box"><div className="box-icon"><Download size={24}/></div><p className="eyebrow">REPO ADDRESS</p><h3>{live?"repo.jimwashkau.com":"Coming with the first release"}</h3><p>{live?"https://repo.jimwashkau.com/":"The install URL will appear here once checkout and downloads are hosted and tested."}</p><div className="box-foot"><span/> {live?"Available now":"Launch preparation in progress"}</div></div></section>
    <footer><div className="footer-top"><div><div className="brand"><span>J.</span> JimWas Repo</div><p>Independent tweaks for a more personal iPhone.</p></div><div><Link href="/packages">Packages</Link><a href="#install">Add repo</a></div></div><div className="footer-bottom">© {new Date().getFullYear()} JimWas Repo <span>Made for the jailbreak community</span></div></footer>
  </main>;
}
